checksumBehavior: update

enableImmutableCache: false

enableImmutableInstalls: false

nodeLinker: node-modules

plugins:
  - path: tools/yarn/plugins/@yarnpkg/plugin-compat.cjs
    spec: '@yarnpkg/plugin-compat'
